# Kaizor OS sysctl configuration

# Shared memory support (needed by many GUI apps)
kern.ipc.shm_allow_removed=1

# Improve responsiveness
kern.sched.preempt_thresh=224

# Networking buffers (smooth browsing/updates)
net.inet.tcp.recvspace=65536
net.inet.tcp.sendspace=65536
